# Generated by Django 3.1.4 on 2021-01-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='decription',
            new_name='description',
        ),
    ]
